# 使用官方 Python 3.10 运行时作为基础镜像
FROM python:3.10-slim

# 设置工作目录为 /app
WORKDIR /app

# 复制项目文件到容器中的 /app
COPY . /app

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# 使用 pip 安装依赖
RUN pip install --upgrade pip \
    && pip install mysqlclient \
    && pip install -r requirements.txt



# 设置环境变量
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# 启动 Flask-SocketIO 应用
CMD ["gunicorn", "app:app", "-c", "./gunicorn.conf.py"]

